version: '3.7'
services:
    app-backend:
        build: ./backend/
        image: app_backend
        container_name: backend
        restart: always
        ports:
            - 5000:5000
    app-frontend:
        build: ./frontend/
        image: app_frontend
        container_name: frontend
        restart: always
        ports:
            - 4200:4200